AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation Template for an AWS Cognito User Pool
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: FootballAppUserPool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireNumbers: true
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: FootballAppUserPoolClient
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO
Outputs:
  UserPoolId:
    Description: ID of the created Cognito User Pool
    Value: !Ref UserPool
  UserPoolClientId:
    Description: ID of the created Cognito User Pool Client
    Value: !Ref UserPoolClient      
  